#!/usr/bin/env bash

set -e

if [[ $# -eq 0 ]]; then
  CONFIG="install-vm.conf.yaml"
else
  if [[ $1 == 'mac' ]]; then
    CONFIG="install.conf.yaml"
  else
    CONFIG="install-vm.conf.yaml"
  fi
fi

echo "Using dotbot config file: ${CONFIG}"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
